name: eletivas
version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3005:3005"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8084:80"
