name: eletivas

services:
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3006:3006"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"
